require('./mdc-button/mdc-button');
require('./mdc-card/mdc-card');
require('./mdc-checkbox/mdc-checkbox');
require('./mdc-dialog/mdc-dialog');
require('./mdc-drawer/mdc-drawer');
require('./mdc-form-field/mdc-form-field');
require('./mdc-grid-list/mdc-grid-list');
require('./mdc-icon/mdc-icon');
require('./mdc-icon-toggle/mdc-icon-toggle');
require('./mdc-list/mdc-list');
require('./mdc-menu/mdc-menu');
require('./mdc-radio/mdc-radio');
require('./mdc-ripple/mdc-ripple');
require('./mdc-select/mdc-select');
require('./mdc-snackbar/mdc-snackbar');
require('./mdc-switch/mdc-switch');
require('./mdc-tabs/mdc-tabs');
require('./mdc-text-field/mdc-text-field');

angular.module('mdc', [
  'mdc.button',
  'mdc.card',
  'mdc.checkbox',
  'mdc.dialog',
  'mdc.drawer',
  'mdc.form-field',
  'mdc.grid-list',
  'mdc.icon',
  'mdc.icon-toggle',
  'mdc.list',
  'mdc.menu',
  'mdc.radio',
  'mdc.ripple',
  'mdc.select',
  'mdc.snackbar',
  'mdc.switch',
  'mdc.tabs',
  'mdc.textfield',
]);
